(()=>{'use strict';
const records=Array.isArray(window.CLUB_CONTENT?.records)?window.CLUB_CONTENT.records:[];
const $=id=>document.getElementById(id), room=$('playlist'), albums=$('mv3Albums'), platter=$('mv3Platter'), dropZone=$('mv3DropZone'), deck=$('mv3Turntable'), play=$('mv3Play'), status=$('mv3Status'), nowTitle=$('mv3NowTitle'), nowLabel=$('mv3NowLabel'), spotify=$('mv3Spotify'), spotifyLink=$('mv3SpotifyLink');
if(!room||!albums||!platter||!dropZone||!deck||!play||!records.length){window.ClubModuleErrors?.push('js/music-v3.js');return;}
const state={selectedId:records[0].id,loadedId:null,phase:'IN_SLEEVE',drag:null,playing:false};
const nodes=new Map();let controller=null,controllerRecord=null,apiPromise=null;
const lang=()=>document.documentElement.lang==='en'?'en':'vi';
const local=v=>typeof v==='string'?v:(v?.[lang()]||v?.vi||v?.en||'');
const copy={vi:{choose:'Chọn album',help:'① Bấm bìa để chọn · ② Giữ chiếc đĩa đang ló ra · ③ Kéo và thả lên mâm.',selected:'Đang chọn',empty:'Chưa có đĩa trên mâm',ready:'Đĩa đã vào đúng tâm mâm. Nhấn Phát nhạc.',miss:'Chưa trúng mâm — đĩa trở về album.',returning:'Đang trả đĩa cũ về album…',drag:'Kéo đĩa tới vùng mâm — máy sẽ hút khi đủ gần.',play:'Phát nhạc',pause:'Tạm dừng',loading:'Đang kết nối Spotify…',playing:'Đang phát từ Spotify.'},en:{choose:'Choose album',help:'① Tap a cover · ② Hold the exposed record · ③ Drag and drop it onto the platter.',selected:'Selected',empty:'No record on the platter',ready:'Record centered on the platter. Press Play.',miss:'Missed the platter — returning to the sleeve.',returning:'Returning the old record to its sleeve…',drag:'Drag the record near the platter — it will snap to center.',play:'Play music',pause:'Pause',loading:'Connecting Spotify…',playing:'Playing from Spotify.'}};
const t=k=>copy[lang()][k]||k;
function rec(id){return records.find(r=>r.id===id)}
function discSize(){const el=nodes.get(state.selectedId)?.disc||nodes.values().next().value?.disc;return el?el.getBoundingClientRect().width:160}
function setStatus(s){status.textContent=s}
function updateText(){document.querySelector('#mv3LibraryTitle').textContent=t('choose');$('mv3Help').textContent=t('help');play.querySelector('b').textContent=state.playing?t('pause'):t('play');renderMeta();}
function renderMeta(){const r=rec(state.loadedId);nowLabel.textContent=r?t('selected'):t('empty');nowTitle.textContent=r?local(r.name):'—';if(r)spotifyLink.href=r.spotifyUrl;}
function makeAlbum(r){const wrap=document.createElement('article');wrap.className='mv3-album';wrap.dataset.record=r.id;wrap.dataset.theme=r.theme;const btn=document.createElement('button');btn.type='button';btn.className='mv3-cover-button';btn.setAttribute('aria-label',`${t('choose')}: ${local(r.name)}`);const cover=document.createElement('span');cover.className='mv3-cover';const ci=document.createElement('img');ci.src=r.image;ci.alt='';ci.draggable=false;cover.append(ci);btn.append(cover);const disc=document.createElement('div');disc.className='mv3-disc';disc.dataset.record=r.id;disc.dataset.theme=r.theme;disc.setAttribute('role','button');disc.setAttribute('tabindex','0');disc.setAttribute('aria-label',local(r.name));const label=document.createElement('span');label.className='mv3-disc-label';const li=document.createElement('img');li.src=r.image;li.alt='';li.draggable=false;label.append(li);disc.append(label);const name=document.createElement('h4');name.className='mv3-name';name.textContent=local(r.name);const cap=document.createElement('p');cap.className='mv3-caption';cap.textContent=local(r.caption);wrap.append(disc,btn,name,cap);albums.append(wrap);nodes.set(r.id,{wrap,btn,disc,name,cap});btn.addEventListener('click',()=>select(r.id));disc.addEventListener('pointerdown',e=>startDrag(e,r.id));disc.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&state.selectedId===r.id){e.preventDefault();setStatus(t('drag'));}});}
records.forEach(makeAlbum);
function syncAlbums(){for(const [id,n] of nodes){const sel=id===state.selectedId;n.wrap.classList.toggle('is-selected',sel);n.disc.classList.toggle('is-enabled',sel||id===state.loadedId);n.btn.setAttribute('aria-pressed',String(sel));n.name.textContent=local(rec(id).name);n.cap.textContent=local(rec(id).caption);n.disc.setAttribute('aria-label',local(rec(id).name));n.btn.setAttribute('aria-label',`${t('choose')}: ${local(rec(id).name)}`);}}
async function select(id){if(id===state.selectedId){syncAlbums();return;} if(state.loadedId&&state.loadedId!==id) await returnLoaded();state.selectedId=id;syncAlbums();setStatus(t('drag'));}
function homeDisc(id,instant=false){const n=nodes.get(id);if(!n)return;const d=n.disc;d.classList.remove('is-dragging','is-on-deck');d.style.cssText='';n.wrap.insertBefore(d,n.btn);if(instant){d.style.transition='none';requestAnimationFrame(()=>d.style.transition='');}}
function centerOf(rect){return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}}
function inDropRange(x,y){const r=dropZone.getBoundingClientRect(),c=centerOf(r),dist=Math.hypot(x-c.x,y-c.y),radius=Math.max(r.width*.82,150);return dist<=radius}
function animateTo(el,targetParent,targetClass,done){const first=el.getBoundingClientRect();targetParent.append(el);el.classList.remove('is-dragging','is-on-deck');if(targetClass)el.classList.add(targetClass);el.style.cssText='';const last=el.getBoundingClientRect();const dx=first.left-last.left,dy=first.top-last.top;const sx=first.width/Math.max(1,last.width);el.animate([{transform:`translate(${dx}px,${dy}px) scale(${sx}) rotate(7deg)`},{transform:'translate(0,0) scale(1) rotate(0deg)'}],{duration:560,easing:'cubic-bezier(.18,.86,.2,1)'}).finished.then(done,done)}
function returnLoaded(){return new Promise(resolve=>{if(!state.loadedId){resolve();return}const id=state.loadedId,n=nodes.get(id),d=n.disc;state.playing=false;deck.classList.remove('is-playing');play.querySelector('b').textContent=t('play');setStatus(t('returning'));const old=id;state.loadedId=null;play.disabled=true;destroyController();animateTo(d,n.wrap,null,()=>{homeDisc(old);state.phase='IN_SLEEVE';syncAlbums();renderMeta();resolve();});});}
function startDrag(e,id){if(e.button!==undefined&&e.button!==0)return;if(state.selectedId!==id||state.drag)return;const n=nodes.get(id),d=n.disc;if(state.loadedId===id)return;const r=d.getBoundingClientRect(),size=r.width;state.phase='DRAGGING';state.drag={id:e.pointerId,recordId:id,disc:d,size,offsetX:e.clientX-r.left,offsetY:e.clientY-r.top};d.setPointerCapture?.(e.pointerId);document.body.append(d);d.classList.add('is-dragging');d.style.width=size+'px';d.style.height=size+'px';move(e);setStatus(t('drag'));window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',end,{once:true});e.preventDefault();}
function move(e){const g=state.drag;if(!g)return;e.preventDefault?.();const left=e.clientX-g.offsetX,top=e.clientY-g.offsetY;g.disc.style.left=left+'px';g.disc.style.top=top+'px';g.disc.style.right='auto';g.disc.style.translate='none';const hot=inDropRange(left+g.size/2,top+g.size/2);deck.classList.toggle('is-hot',hot);}
async function end(e){const g=state.drag;if(!g)return;window.removeEventListener('pointermove',move);state.drag=null;deck.classList.remove('is-hot');const r=g.disc.getBoundingClientRect(),valid=inDropRange(r.left+r.width/2,r.top+r.height/2);if(!valid){const n=nodes.get(g.recordId);animateTo(g.disc,n.wrap,null,()=>{homeDisc(g.recordId);state.phase='IN_SLEEVE';syncAlbums();setStatus(t('miss'));});return}if(state.loadedId&&state.loadedId!==g.recordId)await returnLoaded();state.loadedId=g.recordId;state.selectedId=g.recordId;state.phase='ON_TURNTABLE';animateTo(g.disc,platter,'is-on-deck',()=>{});play.disabled=false;syncAlbums();renderMeta();setStatus(t('ready'));}
function destroyController(){try{controller?.destroy?.()}catch{}controller=null;controllerRecord=null;spotify.replaceChildren();spotify.hidden=true}
function loadApi(){if(window.SpotifyIframeApi)return Promise.resolve(window.SpotifyIframeApi);if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const old=window.onSpotifyIframeApiReady;window.onSpotifyIframeApiReady=api=>{window.SpotifyIframeApi=api;old?.(api);resolve(api)};if(!document.getElementById('mv3SpotifyApi')){const s=document.createElement('script');s.id='mv3SpotifyApi';s.src='https://open.spotify.com/embed/iframe-api/v1';s.async=true;s.onerror=reject;document.head.append(s)}});return apiPromise}
async function ensureController(){const r=rec(state.loadedId);if(!r)return null;if(controller&&controllerRecord===r.id)return controller;destroyController();spotify.hidden=false;setStatus(t('loading'));try{const api=await loadApi();return await new Promise((resolve,reject)=>{const host=document.createElement('div');spotify.append(host);api.createController(host,{width:'100%',height:152,uri:r.uri},c=>{controller=c;controllerRecord=r.id;c.addListener('playback_update',ev=>{const paused=ev?.data?.isPaused!==false;state.playing=!paused;deck.classList.toggle('is-playing',state.playing);play.querySelector('b').textContent=state.playing?t('pause'):t('play');});resolve(c)})})}catch(err){const iframe=document.createElement('iframe');iframe.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';iframe.src=`https://open.spotify.com/embed/playlist/${r.uri.split(':')[2]}?theme=0`;spotify.replaceChildren(iframe);spotify.hidden=false;return null}}
play.addEventListener('click',async()=>{if(!state.loadedId)return;const c=await ensureController();if(c){try{c.togglePlay()}catch{}setStatus(t('playing'))}});
document.addEventListener('club:language',()=>{updateText();syncAlbums()});
syncAlbums();updateText();setStatus(t('drag'));window.ClubMusicV3={state,select,returnLoaded};
})();
