(()=>{'use strict';
const records=Array.isArray(window.CLUB_CONTENT?.records)?window.CLUB_CONTENT.records:[];
const $=id=>document.getElementById(id),room=$('playlist'),albums=$('mv3Albums'),platter=$('mv3Platter'),platterSurface=$('mv3PlatterSurface'),platterDots=$('mv3PlatterDots'),dropZone=$('mv3DropZone'),deck=$('mv3Turntable'),play=$('mv3Play'),status=$('mv3Status'),nowTitle=$('mv3NowTitle'),nowLabel=$('mv3NowLabel'),spotify=$('mv3Spotify'),spotifyLink=$('mv3SpotifyLink');
if(!room||!albums||!platter||!dropZone||!deck||!play||!records.length){window.ClubModuleErrors?.push('js/music-v3.js');return;}
const state={selectedId:records[0].id,loadedId:null,phase:'IN_SLEEVE',drag:null,playing:false,spinAngle:0,spinVelocity:0,trackProgress:0,lastProgress:0,armMode:'REST'};
const nodes=new Map();let controller=null,controllerRecord=null,apiPromise=null,spinRaf=0,lastSpinTime=0,powerTimer=0,armTimers=[];
const lang=()=>document.documentElement.lang==='en'?'en':'vi';
const local=v=>typeof v==='string'?v:(v?.[lang()]||v?.vi||v?.en||'');
const copy={vi:{choose:'Chọn album',help:'① Bấm bìa để chọn · ② Giữ phần đĩa đang ló ra · ③ Kéo và thả lên mâm.',selected:'Đang chọn',empty:'Chưa có đĩa trên mâm',ready:'Đĩa đã vào mâm. Nhấn Phát nhạc.',miss:'Chưa trúng mâm — đĩa trở về album.',returning:'Đang nhấc kim và trả đĩa về album…',drag:'Đưa đĩa tới gần mâm — vùng hút sẽ sáng lên.',play:'Phát nhạc',pause:'Tạm dừng',loading:'Đang kết nối Spotify…',playing:'Máy đang chạy · 33⅓ RPM',cueing:'Đang hạ kim vào rãnh…'},en:{choose:'Choose album',help:'① Tap a cover · ② Hold the exposed record · ③ Drag and drop it onto the platter.',selected:'Selected',empty:'No record on the platter',ready:'Record is on the platter. Press Play.',miss:'Missed the platter — returning to the sleeve.',returning:'Lifting the stylus and returning the record…',drag:'Move the record near the platter — the snap zone will light up.',play:'Play music',pause:'Pause',loading:'Connecting Spotify…',playing:'Playing · 33⅓ RPM',cueing:'Lowering the stylus into the groove…'}};
const t=k=>copy[lang()][k]||k;
function rec(id){return records.find(r=>r.id===id)}
function setStatus(s){if(status)status.textContent=s}
function clearArmTimers(){armTimers.forEach(clearTimeout);armTimers=[]}
function armLater(ms,fn){const id=setTimeout(()=>{armTimers=armTimers.filter(x=>x!==id);fn()},ms);armTimers.push(id);return id}
function clearPowerTimer(){if(powerTimer){clearTimeout(powerTimer);powerTimer=0}}
const ARM={rest:-17.5,outer:0,inner:9.5,lift:-3.5};
function armAngleFor(progress){const p=Math.max(0,Math.min(1,Number(progress)||0));return ARM.outer+(ARM.inner-ARM.outer)*p}
function setArm(angle,lift=0,mode='TRACKING',time=650,ease='cubic-bezier(.22,.72,.18,1)'){state.armAngle=angle;deck.style.setProperty('--arm-angle',`${angle}deg`);deck.style.setProperty('--arm-lift',`${lift}px`);deck.style.setProperty('--arm-time',`${time}ms`);deck.style.setProperty('--arm-ease',ease);deck.classList.toggle('is-arm-lifted',lift<0);deck.dataset.armMode=mode.toLowerCase();state.armMode=mode}
function armRest(immediate=false){clearArmTimers();const current=Number.isFinite(state.armAngle)?state.armAngle:ARM.rest;if(immediate){setArm(ARM.rest,0,'REST',0);return}setArm(current,ARM.lift,'LIFTING',360,'cubic-bezier(.22,.72,.18,1)');armLater(380,()=>setArm(ARM.rest,ARM.lift,'RETURNING',1050,'cubic-bezier(.18,.82,.18,1)'));armLater(1460,()=>setArm(ARM.rest,0,'REST',360,'cubic-bezier(.25,.75,.2,1)'))}
function armCue(progress=state.trackProgress){clearArmTimers();const target=armAngleFor(progress),current=Number.isFinite(state.armAngle)?state.armAngle:ARM.rest;setArm(current,ARM.lift,'LIFTING',360,'cubic-bezier(.22,.72,.18,1)');armLater(380,()=>setArm(target,ARM.lift,'CUEING',1100,'cubic-bezier(.18,.82,.18,1)'));armLater(1510,()=>{if(state.playing)setArm(target,0,'TRACKING',380,'cubic-bezier(.25,.75,.2,1)')})}
function updateArmProgress(progress){const next=Math.max(0,Math.min(1,Number(progress)||0)),prev=state.trackProgress;state.trackProgress=next;if(!state.playing||state.armMode==='CUEING'||state.armMode==='RETURNING'||state.armMode==='LIFTING')return;const jump=Math.abs(next-prev);setArm(armAngleFor(next),0,'TRACKING',jump>.035?520:1100,jump>.035?'cubic-bezier(.2,.78,.2,1)':'linear')}
function updateText(){const title=$('mv3LibraryTitle'),help=$('mv3Help');if(title)title.textContent=t('choose');if(help)help.textContent=t('help');play.querySelector('b').textContent=state.playing?t('pause'):t('play');renderMeta();syncAlbums()}
function renderMeta(){const r=rec(state.loadedId);nowLabel.textContent=r?t('selected'):t('empty');nowTitle.textContent=r?local(r.name):'—';if(r)spotifyLink.href=r.spotifyUrl}
function makeAlbum(r){
  const wrap=document.createElement('article');wrap.className='mv3-album';wrap.dataset.record=r.id;wrap.dataset.theme=r.theme;
  const visual=document.createElement('div');visual.className='mv3-album-visual';
  const btn=document.createElement('button');btn.type='button';btn.className='mv3-cover-button';btn.setAttribute('aria-label',`${t('choose')}: ${local(r.name)}`);
  const cover=document.createElement('span');cover.className='mv3-cover';const ci=document.createElement('img');ci.src=r.image;ci.alt='';ci.draggable=false;cover.append(ci);btn.append(cover);
  const coverTitle=document.createElement('span');coverTitle.className='mv3-cover-title';coverTitle.textContent=local(r.name);btn.append(coverTitle);
  const selected=document.createElement('span');selected.className='mv3-selected-tag';selected.textContent=t('selected');btn.append(selected);
  const disc=document.createElement('div');disc.className='mv3-disc';disc.dataset.record=r.id;disc.dataset.theme=r.theme;disc.setAttribute('role','button');disc.setAttribute('tabindex','0');disc.setAttribute('aria-label',local(r.name));
  const surface=document.createElement('span');surface.className='mv3-disc-surface';
  const label=document.createElement('span');label.className='mv3-disc-label';const li=document.createElement('img');li.src=r.image;li.alt='';li.draggable=false;label.append(li);surface.append(label);disc.append(surface);
  const name=document.createElement('h4');name.className='mv3-name';name.textContent=local(r.name);const cap=document.createElement('p');cap.className='mv3-caption';cap.textContent=local(r.caption);
  visual.append(disc,btn);wrap.append(visual,name,cap);albums.append(wrap);nodes.set(r.id,{wrap,visual,btn,disc,surface,name,cap,selected,coverTitle});
  btn.addEventListener('click',()=>select(r.id));disc.addEventListener('pointerdown',e=>startDrag(e,r.id));disc.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&state.selectedId===r.id){e.preventDefault();setStatus(t('drag'))}})
}
records.forEach(makeAlbum);
function syncAlbums(){for(const [id,n] of nodes){const sel=id===state.selectedId,r=rec(id);n.wrap.classList.toggle('is-selected',sel);n.disc.classList.toggle('is-enabled',sel||id===state.loadedId);n.btn.setAttribute('aria-pressed',String(sel));n.name.textContent=local(r.name);n.coverTitle.textContent=local(r.name);n.cap.textContent=local(r.caption);n.disc.setAttribute('aria-label',local(r.name));n.btn.setAttribute('aria-label',`${t('choose')}: ${local(r.name)}`);n.selected.textContent=t('selected')}}
async function select(id){if(id===state.selectedId){syncAlbums();return}if(state.loadedId&&state.loadedId!==id)await returnLoaded();state.selectedId=id;syncAlbums();setStatus(t('drag'))}
function homeDisc(id,instant=false){const n=nodes.get(id);if(!n)return;const d=n.disc;d.classList.remove('is-dragging','is-on-deck');d.style.cssText='';n.surface.style.transform='';n.visual.insertBefore(d,n.btn);if(instant){d.style.transition='none';requestAnimationFrame(()=>d.style.transition='')}}
function centerOf(rect){return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}}
function inDropRange(x,y){const r=dropZone.getBoundingClientRect(),c=centerOf(r),dist=Math.hypot(x-c.x,y-c.y),radius=Math.max(r.width*.92,160);return dist<=radius}
function animateTo(el,targetParent,targetClass,done){const first=el.getBoundingClientRect();targetParent.append(el);el.classList.remove('is-dragging','is-on-deck');if(targetClass)el.classList.add(targetClass);el.style.cssText='';const last=el.getBoundingClientRect();const dx=first.left-last.left,dy=first.top-last.top,sx=first.width/Math.max(1,last.width);const anim=el.animate([{transform:`translate(${dx}px,${dy}px) scale(${sx}) rotate(4deg)`},{transform:'translate(0,0) scale(1) rotate(0deg)'}],{duration:680,easing:'cubic-bezier(.16,.86,.18,1)'});anim.finished.then(()=>{el.style.transform='';done?.()},()=>{el.style.transform='';done?.()})}
function startSpinLoop(){if(spinRaf)return;lastSpinTime=performance.now();spinRaf=requestAnimationFrame(spinFrame)}
function spinFrame(now){const dt=Math.min(48,Math.max(0,now-lastSpinTime));lastSpinTime=now;const target=state.playing?0.2:0,tau=state.playing?1250:1500,k=1-Math.exp(-dt/tau);state.spinVelocity+=(target-state.spinVelocity)*k;state.spinAngle=(state.spinAngle+state.spinVelocity*dt)%360;const loaded=state.loadedId?nodes.get(state.loadedId):null;if(loaded?.surface&&loaded.disc.classList.contains('is-on-deck'))loaded.surface.style.transform=`rotate(${state.spinAngle}deg)`;if(platterSurface)platterSurface.style.transform=`rotate(${state.spinAngle*.60}deg)`;if(platterDots)platterDots.style.transform=`rotate(${state.spinAngle*.84}deg)`;if(state.playing||Math.abs(state.spinVelocity)>.00025){spinRaf=requestAnimationFrame(spinFrame)}else{spinRaf=0;state.spinVelocity=0}}
function beginMechanicalPlayback(progress=state.trackProgress){if(state.playing){updateArmProgress(progress);return}clearPowerTimer();deck.classList.add('is-power-on');state.playing=true;deck.classList.add('is-playing');play.querySelector('b').textContent=t('pause');setStatus(t('cueing'));startSpinLoop();armCue(progress);armLater(1370,()=>{if(state.playing)setStatus(t('playing'))})}
function stopMechanicalPlayback({powerOff=true,immediate=false}={}){if(!state.playing&&!immediate){if(powerOff)deck.classList.remove('is-power-on');return}state.playing=false;deck.classList.remove('is-playing');play.querySelector('b').textContent=t('play');startSpinLoop();armRest(immediate);if(powerOff){clearPowerTimer();powerTimer=setTimeout(()=>deck.classList.remove('is-power-on'),immediate?0:1050)}setStatus(state.loadedId?t('ready'):t('empty'))}
function setPlayingFromSpotify(on,progress=state.trackProgress){if(on){if(!state.playing)beginMechanicalPlayback(progress);else updateArmProgress(progress)}else if(state.playing)stopMechanicalPlayback()}
function destroyController(){try{controller?.destroy?.()}catch{}controller=null;controllerRecord=null;spotify.replaceChildren();spotify.hidden=true}
function returnLoaded(){return new Promise(resolve=>{if(!state.loadedId){resolve();return}const id=state.loadedId,n=nodes.get(id),d=n.disc;stopMechanicalPlayback({powerOff:true});deck.classList.remove('is-loaded');play.disabled=true;setStatus(t('returning'));const old=id;state.loadedId=null;destroyController();setTimeout(()=>animateTo(d,n.visual,null,()=>{homeDisc(old);state.phase='IN_SLEEVE';state.trackProgress=0;state.lastProgress=0;syncAlbums();renderMeta();resolve()}),720)})}
function startDrag(e,id){if(e.button!==undefined&&e.button!==0)return;if(state.selectedId!==id||state.drag)return;const n=nodes.get(id),d=n.disc;if(state.loadedId===id)return;const r=d.getBoundingClientRect(),size=r.width;state.phase='DRAGGING';state.drag={id:e.pointerId,recordId:id,disc:d,size,offsetX:e.clientX-r.left,offsetY:e.clientY-r.top};d.setPointerCapture?.(e.pointerId);document.body.append(d);d.classList.add('is-dragging');d.style.width=size+'px';d.style.height=size+'px';move(e);setStatus(t('drag'));window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',end,{once:true});e.preventDefault()}
function move(e){const g=state.drag;if(!g)return;e.preventDefault?.();const left=e.clientX-g.offsetX,top=e.clientY-g.offsetY;g.disc.style.left=left+'px';g.disc.style.top=top+'px';g.disc.style.right='auto';g.disc.style.translate='none';deck.classList.toggle('is-hot',inDropRange(left+g.size/2,top+g.size/2))}
async function end(){const g=state.drag;if(!g)return;window.removeEventListener('pointermove',move);state.drag=null;deck.classList.remove('is-hot');const r=g.disc.getBoundingClientRect(),valid=inDropRange(r.left+r.width/2,r.top+r.height/2);if(!valid){const n=nodes.get(g.recordId);animateTo(g.disc,n.visual,null,()=>{homeDisc(g.recordId);state.phase='IN_SLEEVE';syncAlbums();setStatus(t('miss'))});return}if(state.loadedId&&state.loadedId!==g.recordId)await returnLoaded();state.loadedId=g.recordId;state.selectedId=g.recordId;state.phase='ON_TURNTABLE';state.trackProgress=0;state.lastProgress=0;animateTo(g.disc,platter,'is-on-deck',()=>{g.disc.querySelector('.mv3-disc-surface').style.transform=`rotate(${state.spinAngle}deg)`});deck.classList.add('is-loaded');armRest(true);play.disabled=false;syncAlbums();renderMeta();setStatus(t('ready'));ensureController().catch(()=>{})}
function loadApi(){if(window.SpotifyIframeApi)return Promise.resolve(window.SpotifyIframeApi);if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const old=window.onSpotifyIframeApiReady;window.onSpotifyIframeApiReady=api=>{window.SpotifyIframeApi=api;old?.(api);resolve(api)};if(!document.getElementById('mv3SpotifyApi')){const s=document.createElement('script');s.id='mv3SpotifyApi';s.src='https://open.spotify.com/embed/iframe-api/v1';s.async=true;s.onerror=reject;document.head.append(s)}});return apiPromise}
function handlePlaybackUpdate(ev){const d=ev?.data||{},paused=d.isPaused!==false,duration=Number(d.duration)||0,position=Number(d.position)||0,progress=duration>0?Math.max(0,Math.min(1,position/duration)):state.trackProgress;const wrapped=state.lastProgress>.82&&progress<.18&&!paused;state.lastProgress=progress;updateArmProgress(progress);if(wrapped){armRest();setTimeout(()=>{if(!paused&&state.loadedId)armCue(progress)},1850)}setPlayingFromSpotify(!paused,progress)}
async function ensureController(){const r=rec(state.loadedId);if(!r)return null;if(controller&&controllerRecord===r.id)return controller;destroyController();spotify.hidden=false;setStatus(t('loading'));try{const api=await loadApi();return await new Promise(resolve=>{const host=document.createElement('div');spotify.append(host);api.createController(host,{width:'100%',height:152,uri:r.uri},c=>{controller=c;controllerRecord=r.id;c.addListener('playback_update',handlePlaybackUpdate);resolve(c)})})}catch(err){const iframe=document.createElement('iframe');iframe.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';iframe.src=`https://open.spotify.com/embed/playlist/${r.uri.split(':')[2]}?theme=0`;spotify.replaceChildren(iframe);spotify.hidden=false;return null}}
play.addEventListener('click',async()=>{if(!state.loadedId)return;play.disabled=true;const wanted=!state.playing;setStatus(t('loading'));const c=await ensureController();play.disabled=false;if(c){try{c.togglePlay();setStatus(wanted?t('cueing'):t('ready'));return}catch{}}if(wanted)beginMechanicalPlayback(state.trackProgress);else stopMechanicalPlayback()});
document.addEventListener('club:language',()=>{updateText();syncAlbums()});
syncAlbums();updateText();renderMeta();setStatus(t('drag'));armRest(true);window.ClubMusicV3={state,select,returnLoaded,stopMechanicalPlayback,beginMechanicalPlayback};
})();
