/* Raven Lin / Driver sequence v6.2.0 - CSS timeline, Safari/iOS friendly. */
const A=n=>new URL(`../../assets/raven/${n}`,import.meta.url).href;
const ASSETS={base:A('base.webp'),white:A('white_buckle.webp'),red:A('red_buckle.webp'),revolve:A('angled.webp'),final:A('final.webp')};
const DURATION=5200; let singleton;
export function initRaven(){
 if(singleton)return singleton; let active=null,preloadPromise=null,lastError='';
 const preload=()=>preloadPromise||=(Promise.all(Object.values(ASSETS).map(src=>new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(src);i.onerror=()=>no(new Error(`Missing Raven asset: ${src}`));i.src=src}))).catch(e=>{preloadPromise=null;lastError=String(e?.message||e);throw e}));
 const stop=(reason='cancelled')=>{if(!active)return;const {layer,timer,trigger}=active;active=null;clearTimeout(timer);layer.classList.add('rv62-out');setTimeout(()=>layer.remove(),180);document.documentElement.classList.remove('raven-sequence-running');document.dispatchEvent(new CustomEvent('club:raven',{detail:{active:false,reason}}));if(reason==='complete')document.querySelector('.raven-empty')?.classList.add('rv62-profile-hit');if(reason!=='replaced'&&reason!=='complete'&&trigger?.isConnected)trigger.focus?.({preventScroll:true})};
 const sparks=()=>Array.from({length:18},(_,i)=>`<i style="--a:${(i*137.5)%360}deg;--d:${90+(i%6)*35}px;--s:${2+(i%4)}px;--delay:${(i%5)*18}ms"></i>`).join('');
 const markup=en=>`<div class="rv62-bg"></div><div class="rv62-grid"></div><div class="rv62-flash"></div><header class="rv62-head"><span><b></b> RAVEN // 03</span><button type="button" data-rv62-skip>${en?'SKIP':'BỎ QUA'}</button></header><main class="rv62-scene"><div class="rv62-word rv62-word-set">SET</div><div class="rv62-word rv62-word-revolve">REVOLVE</div><div class="rv62-stage"><img class="rv62-base" src="${ASSETS.base}" alt=""><img class="rv62-buckle rv62-white" src="${ASSETS.white}" alt=""><img class="rv62-buckle rv62-red" src="${ASSETS.red}" alt=""><img class="rv62-revolve" src="${ASSETS.revolve}" alt=""><div class="rv62-final">${[0,1,2,3,4,5].map(i=>`<span class="rv62-panel rv62-p${i}"><img src="${ASSETS.final}" alt=""></span>`).join('')}<img class="rv62-final-core" src="${ASSETS.final}" alt=""></div><div class="rv62-ring rv62-r1"></div><div class="rv62-ring rv62-r2"></div><div class="rv62-particles">${sparks()}</div></div><div class="rv62-henshin">HENSHIN</div><div class="rv62-name"><small>ARTIST 03 // ENTRY COMPLETE</small><strong>RAVEN <em>LIN</em></strong><span>${en?'ARTWORK ARCHIVE // COMING SOON':'KHO TÁC PHẨM // SẮP RA MẮT'}</span></div></main><footer class="rv62-foot"><span>DESIRE DRIVER // RAVEN</span><i><b></b></i><span>05.2 SEC</span></footer>`;
 async function launch(trigger,{explicit=false}={}){stop('replaced');lastError='';try{await preload()}catch(e){console.error('[Raven v6.2]',e);return false}if(document.hidden)return false;const layer=document.createElement('div');layer.className='raven-henshin-layer rv62';layer.dataset.userRequested=explicit?'true':'false';layer.innerHTML=markup(document.documentElement.lang==='en');document.body.append(layer);document.documentElement.classList.add('raven-sequence-running');void layer.offsetWidth;layer.classList.add('rv62-run');const timer=setTimeout(()=>stop('complete'),DURATION+180);active={layer,timer,trigger,started:performance.now()};layer.querySelector('[data-rv62-skip]').addEventListener('click',()=>stop('skipped'),{once:true});document.dispatchEvent(new CustomEvent('club:raven',{detail:{active:true,duration:DURATION}}));return true}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active){e.preventDefault();stop('escape')}});window.addEventListener('pagehide',()=>stop('hidden'));
 singleton={launch,stop,preload,get state(){return{version:'6.2.0',active:!!active,duration:DURATION,lastError}}};window.ClubRaven=singleton;return singleton;
}
