from pathlib import Path
from playwright.sync_api import sync_playwright
from harness import load_site
import json,time,os
ROOT=Path(__file__).resolve().parents[1];OUT=Path(__file__).resolve().parent/'results';OUT.mkdir(exist_ok=True)
results=[]
def check(name,ok,detail=None):
 results.append({'test':name,'pass':bool(ok),'detail':detail});print(('PASS' if ok else 'FAIL'),name,detail or '')
 if not ok: raise AssertionError(name)
def ready(p):p.wait_for_function('document.documentElement.dataset.appReady === "true"')
def music(p):
 p.locator('#playlist').scroll_into_view_if_needed();p.wait_for_function('window.ClubMusicV4 !== undefined');p.locator('#mv3Turntable').scroll_into_view_if_needed();p.wait_for_timeout(200)
def state(p):return p.evaluate('({...window.ClubMusicV4.state,active:window.ClubMusicV4.animationActive})')
def place_keyboard(p,id):
 p.locator(f'[data-choose-record="{id}"]').click();p.wait_for_function('(id)=>ClubMusicV4.state.selectedId===id&&ClubMusicV4.state.phase==="IN_SLEEVE"',arg=id)
 p.locator(f'.mv3-disc[data-record="{id}"]').focus();p.keyboard.press('Enter');p.wait_for_function('(id)=>ClubMusicV4.state.loadedId===id&&ClubMusicV4.state.phase==="ON_TURNTABLE"',arg=id)
 p.locator('#mv3Turntable').scroll_into_view_if_needed();p.wait_for_timeout(150)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or None,args=['--no-sandbox'])
 p=b.new_page(viewport={'width':1440,'height':1000});err=[];p.on('pageerror',lambda e:err.append(str(e)))
 served=load_site(p,ROOT,spotify=True);ready(p);p.wait_for_timeout(300)
 check('Music module is deferred on the home screen',p.evaluate('!window.ClubMusicV4'))
 check('No Spotify request at first load',p.evaluate('window.__spotifyTest === undefined'))
 check('No full artwork is requested at first load',not any(x['name'].startswith('assets/gallery/') and '/thumbs/' not in x['name'] for x in served))
 r=p.locator('.hero-logo').bounding_box();p.mouse.click(r['x']+r['width']/2,r['y']+r['height']/2);check('Hero mascot opens',p.locator('#mascotCard').get_attribute('aria-hidden')=='false');p.keyboard.press('Escape')
 check('Hero mascot closes',p.locator('#mascotCard').get_attribute('aria-hidden')=='true')
 p.locator('#artistSwitcher').scroll_into_view_if_needed();p.wait_for_function('window.ClubDiagnostics().modules.gallery === "ready"');p.wait_for_timeout(300)
 check('Haruko has six preserved artworks',p.locator('#galleryGrid button[data-index]').count()==6)
 p.locator('[data-filter="digital-art"]').click();check('Digital filter shows Merina only',p.locator('#galleryGrid button[data-index]').count()==1 and 'Merina' in p.locator('#galleryGrid').inner_text())
 p.locator('#galleryGrid button[data-index]').click();p.wait_for_timeout(200)
 check('Lightbox loads the full original on demand',p.locator('#lightbox').evaluate('(e)=>e.open') and any(x['name']=='assets/gallery/merina.webp' for x in served))
 p.keyboard.press('Escape');check('Escape unlocks scrolling',p.locator('body').evaluate('(e)=>!e.classList.contains("no-scroll")'))
 p.locator('[data-artist="akiko-oishi"]').click();p.wait_for_timeout(800)
 check('Akiko has six works without invented titles',p.locator('#galleryGrid button[data-index]').count()==6 and p.locator('#galleryGrid .gallery-info h3').count()==0)
 check('Akiko UFO activates',p.evaluate('!!window.ClubAkikoFlight?.state.active'))
 p.keyboard.press('Escape');check('Akiko escape clears overlay',p.locator('.af253-layer').count()==0)
 p.locator('[data-artist="bao-tam"]').click();p.wait_for_timeout(150)
 check('Haruko garden activates',p.evaluate('document.documentElement.dataset.harukoVisible === "true"'))
 music(p);check('Garden hides after leaving gallery',p.evaluate('document.documentElement.dataset.harukoVisible === "false"'))
 check('Two covers and two physical records',p.locator('.mv3-cover-button').count()==2 and p.locator('.mv3-disc').count()==2)
 # A genuine mouse drag from the exposed rim to the spindle.
 p.locator('#mv3Albums').scroll_into_view_if_needed();p.wait_for_timeout(400)
 disc=p.locator('.mv3-disc[data-record="studio"]');r=disc.bounding_box();dest=p.locator('#mv3DropZone').bounding_box();x=r['x']+r['width']*.94;y=r['y']+r['height']*.5
 check('Record rim is hit-testable',p.evaluate('([x,y])=>!!document.elementFromPoint(x,y)?.closest(".mv3-disc")',[x,y]))
 p.evaluate('window.__originalDisc=document.querySelector(".mv3-disc[data-record=studio]")')
 p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+25,y+20,steps=6);p.wait_for_timeout(80)
 check('Dragging moves the same node out of the sleeve',p.evaluate('window.__originalDisc.parentElement===document.body && document.querySelectorAll(".mv3-disc[data-record=studio]").length===1'))
 p.mouse.move(dest['x']+dest['width']/2+r['width']*.44,dest['y']+dest['height']/2,steps=18);p.wait_for_timeout(70);p.mouse.up()
 p.wait_for_function('ClubMusicV4.state.phase === "ON_TURNTABLE"');p.locator('#mv3Turntable').scroll_into_view_if_needed();p.wait_for_timeout(150)
 check('Drop places the same disc on the platter',p.evaluate('window.__originalDisc.parentElement.id === "mv3Platter"'))
 centers=p.evaluate('''()=>{const a=document.querySelector('.mv3-disc.is-on-deck').getBoundingClientRect(),b=document.querySelector('.mv3-spindle').getBoundingClientRect();return [Math.abs(a.x+a.width/2-b.x-b.width/2),Math.abs(a.y+a.height/2-b.y-b.height/2)]}''')
 check('Record is centered on the spindle within one pixel',max(centers)<1,centers)
 check('Mounting does not autoplay',not state(p)['playing'])
 p.wait_for_function('window.__spotifyTest?.controllers.length===1');p.wait_for_timeout(50);p.locator('#mv3Play').click();p.wait_for_timeout(1900)
 check('Real-shaped Spotify event drives playback',state(p)['playing'])
 angle1=state(p)['spinAngle'];p.wait_for_timeout(170);check('Disc rotates after playback',abs(state(p)['spinAngle']-angle1)>1)
 p.evaluate('window.__spotifyTest.controllers.at(-1).update(140000)');p.wait_for_timeout(900)
 check('Needle follows a seek event',state(p)['trackProgress']==.7 and state(p)['armAngle']>25)
 p.screenshot(path=str(OUT/'v4-music-playing.png'))
 p.locator('#home').scroll_into_view_if_needed();p.wait_for_timeout(300)
 check('Offscreen motor stops RAF without stopping audio',state(p)['playing'] and not state(p)['active'],state(p))
 p.locator('#mv3Turntable').scroll_into_view_if_needed();p.wait_for_timeout(300);check('Motor resumes when visible',state(p)['active'])
 p.locator('#motionDock summary').click();p.locator('#motionMode').select_option('off');p.wait_for_timeout(150)
 check('Motion off keeps audio but stops visual motor',state(p)['playing'] and not state(p)['active'])
 p.locator('#motionMode').select_option('full');p.locator('#motionDock summary').click();p.wait_for_timeout(150)
 check('Explicit full mode resumes visual motor',state(p)['active'])
 p.locator('#mv3Play').click();p.wait_for_timeout(1900);check('Pause parks the arm',not state(p)['playing'] and state(p)['armMode']=='REST')
 # Changing cover returns old disc; no v2 clone or stale handlers survive.
 p.locator('[data-choose-record="pink"]').click();p.wait_for_function('ClubMusicV4.state.selectedId==="pink" && ClubMusicV4.state.phase === "IN_SLEEVE"')
 check('Changing album returns prior disc to the right sleeve',p.evaluate('document.querySelector(".mv3-disc[data-record=studio]").parentElement.classList.contains("mv3-album-visual")'))
 p.evaluate('window.__spotifyTest.controllers[0].emit("playback_update",{isPaused:false,duration:200000,position:180000})');check('Stale Spotify event cannot restart audio visuals',not state(p)['playing'])
 place_keyboard(p,'pink');check('Keyboard can place the selected disc',state(p)['loadedId']=='pink')
 p.locator('.lang-toggle').click();p.wait_for_timeout(150);check('Language switch keeps the physical record loaded',state(p)['loadedId']=='pink' and p.locator('#mv3NowTitle').inner_text()=='A little daydream')
 p.locator('.lang-toggle').click();check('Vietnamese names are restored',p.locator('#mv3NowTitle').inner_text()=='Mơ một chút')
 check('No page exceptions across interactions',not err,err);check('No module errors',p.evaluate('ClubDiagnostics().errors.length===0'))
 p.close()
 # Layout regressions in VI + EN, including the album shelf and controls.
 for width in [320,360,390,430,768,980,1024,1280,1440,1920]:
  p=b.new_page(viewport={'width':width,'height':900});load_site(p,ROOT);ready(p)
  for lang in ['vi','en']:
   p.evaluate('(lang)=>window.Club.setLanguage(lang)',lang);p.wait_for_timeout(30)
   check(f'{width}px {lang}: no horizontal page overflow',p.evaluate('document.documentElement.scrollWidth<=document.documentElement.clientWidth+1'))
   music(p)
   check(f'{width}px {lang}: play control stays inside deck',p.locator('#mv3Play').evaluate('''e=>{const a=e.getBoundingClientRect(),b=e.closest('.mv3-turntable').getBoundingClientRect();return a.left>=b.left&&a.right<=b.right&&a.bottom<=b.bottom+1}'''))
  if width==390:p.screenshot(path=str(OUT/'v4-mobile-music.png'))
  p.close()
 b.close()
OUT.joinpath('browser-tests.json').write_text(json.dumps({'tests':results,'passed':sum(x['pass'] for x in results)},ensure_ascii=False,indent=2))
print('TOTAL',len(results))
