"""Optional maintenance command. Requires Pillow; never modifies a source artwork.
Usage: python tools/optimize-images.py && node tools/release.mjs 4.0.1
"""
from pathlib import Path
import hashlib, io, json, subprocess
from PIL import Image, ImageOps
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets' / 'optimized'
OUT.mkdir(parents=True, exist_ok=True)
sandbox_script = "const fs=require('node:fs'),vm=require('node:vm');const s={window:{}};vm.runInNewContext(fs.readFileSync(process.argv[1],'utf8'),s,{timeout:1000});console.log(JSON.stringify(s.window.CLUB_CONTENT));"
content = json.loads(subprocess.check_output(['node', '-e', sandbox_script, str(ROOT/'content.js')], text=True))
manifest = {}
def variants(source: str, widths: list[int], quality: int = 84) -> None:
    p = (ROOT/source).resolve()
    if not p.is_relative_to(ROOT) or not p.is_file():
        raise FileNotFoundError(f'Local original not found: {source}')
    with Image.open(p) as raw:
        if getattr(raw, 'n_frames', 1) > 1:
            # Do not silently flatten user-supplied animation.
            return
        image = ImageOps.exif_transpose(raw)
        outputs = []
        for width in sorted(set(min(x, image.width) for x in widths)):
            height = round(image.height * width / image.width)
            thumb = image.resize((width, height), Image.Resampling.LANCZOS)
            data = io.BytesIO(); thumb.save(data, format='WEBP', quality=quality, method=6)
            payload = data.getvalue()
            filename = f'{p.stem}-{width}-{hashlib.sha256(payload).hexdigest()[:8]}.webp'
            (OUT/filename).write_bytes(payload)
            outputs.append({'src': f'assets/optimized/{filename}', 'width': width, 'height': height})
        manifest[source] = {'width': image.width, 'height': image.height, 'variants': outputs}
variants('assets/logo-new.jpeg', [96, 192, 640, 960], 87)
variants('assets/disc-pink.jpeg', [160, 540], 86)
variants('assets/gallery/akiko/mascot-intact-v253.webp', [160, 480], 90)
for record in content.get('records', []):
    if record['image'] not in manifest: variants(record['image'], [160, 540], 86)
for artist in content.get('artists', []):
    source = artist.get('mascot')
    if source and source not in manifest: variants(source, [160, 480], 90)
for artwork in content.get('artworks', []):
    variants(artwork['image'], [360, 560])
    if artwork.get('thumb') and artwork['image'] in manifest:
        manifest[artwork['thumb']] = manifest[artwork['image']]
serialized = json.dumps(manifest, ensure_ascii=False, indent=2)
(ROOT/'assets/image-manifest.json').write_text(serialized + '\n', encoding='utf8')
(ROOT/'js/data/images.js').write_text('// Generated by tools/optimize-images.py. Originals are unchanged.\nexport const images = ' + serialized + ';\n', encoding='utf8')
print(f'Created responsive images for {len(manifest)} source references. Originals untouched.')
print('Next: node tools/release.mjs <new-version> && node tools/validate.mjs')
