/** Single release command: regenerate fallback gallery, stamp every local runtime import. */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const file = name => path.join(root, name);
const manifest = JSON.parse(fs.readFileSync(file('release.json'), 'utf8'));
const version = process.argv[2] || manifest.version;
if (!/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(version)) throw new Error('Use a semantic version, for example 4.0.1');
manifest.version = version;
fs.writeFileSync(file('release.json'), JSON.stringify(manifest, null, 2) + '\n');
fs.writeFileSync(file('js/core/build.js'), `// Generated by tools/release.mjs; edit release.json instead.\nexport const VERSION = ${JSON.stringify(version)};\n`);
const stamp = text => text.replace(/(["'])(\.{1,2}\/[^"'\s]+?\.(?:js|css))(?:\?v=[^"']*)?\1/g, (_, q, rel) => `${q}${rel}?v=${version}${q}`);
function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (p.endsWith('.js')) fs.writeFileSync(p, stamp(fs.readFileSync(p, 'utf8')));
  }
}
walk(file('js'));
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(file('content.js'), 'utf8'), sandbox, { timeout: 1000 });
const data = sandbox.window.CLUB_CONTENT;
const images = JSON.parse(fs.readFileSync(file('assets/image-manifest.json'), 'utf8'));
const esc = str => String(str ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const vi = val => typeof val === 'string' ? val : val?.vi || val?.en || '';
const artist = data.artists?.[0];
const artworks = (data.artworks || []).map((art, index) => ({art, index})).filter(({art}) => !artist || art.artistId === artist.id);
const cards = artworks.slice(0, 12).map(({art, index}) => {
  const src = art.thumb || art.image, entry = images[src];
  const variants = entry?.variants || [];
  const image = variants.find(v => v.width >= 560) || variants.at(-1);
  const set = variants.map(v => `${v.src} ${v.width}w`).join(', ');
  const title = vi(art.title), alt = title || `${vi(art.author)} - ${vi(art.description)}`;
  return `<button type="button" class="gallery-card${title ? '' : ' gallery-card-no-title'}" data-index="${index}" aria-label="${esc(alt)}"><img src="${esc(image?.src || src)}"${set ? ` srcset="${esc(set)}"` : ''} sizes="(max-width:640px) 44vw, (max-width:980px) 42vw, 380px" width="${entry?.width || 560}" height="${entry?.height || 720}" alt="${esc(alt)}" loading="lazy" decoding="async" fetchpriority="low" draggable="false"><div class="gallery-info">${title ? `<h3>${esc(title)}</h3>` : ''}<p>${esc(vi(art.description))}</p></div></button>`;
}).join('');
const heading = artist ? `<div class="gallery-author"><span class="gallery-author-kicker">T\u00c1C GI\u1ea2</span><h3>${esc(vi(artist.label))} ${esc(vi(artist.name))}</h3><p>${artworks.length} t\u00e1c ph\u1ea9m</p></div>` : '';
let html = fs.readFileSync(file('index.html'), 'utf8');
if (!html.includes('<!-- v4:gallery:start -->')) throw new Error('Missing fallback gallery markers');
html = html.replace(/(<!-- v4:gallery:start -->)[\s\S]*?(<!-- v4:gallery:end -->)/, (_, a, b) => a + heading + cards + b);
// Responsive static logos are refreshed too, after changing their original artwork.
html = html.replace(/<img\b[^>]*>/g, tag => {
  const src = tag.match(/data-image-source="([^"]+)"/)?.[1];
  const entry = images[src]; if (!entry) return tag;
  const width = Number(tag.match(/data-image-width="(\d+)"/)?.[1] || 192);
  const choice = entry.variants.find(v => v.width >= width) || entry.variants.at(-1);
  const attrs = { src: choice.src, srcset: entry.variants.map(v => `${v.src} ${v.width}w`).join(', '), width: entry.width, height: entry.height };
  for (const [key,val] of Object.entries(attrs)) tag = tag.replace(new RegExp(`\\s${key}="[^"]*"`), ` ${key}="${esc(val)}"`);
  return tag;
});
html = html.replace(/data-build="[^"]*"/, `data-build="${version}"`);
html = html.replace(/((?:src|href)=["'])((?:\.\/)?(?:content\.js|js\/[^"'?]+\.js|css\/[^"'?]+\.css))(?:\?v=[^"']*)?(["'])/g, (_, a, rel, q) => `${a}${rel}?v=${version}${q}`);
html = html.replace(/(<[^>]+id="buildStatus"[^>]*>)[^<]*(<\/[^>]+>)/, `$1v${version}$2`);
fs.writeFileSync(file('index.html'), html);
console.log(`Release ${version}: runtime imports and fallback gallery regenerated.`);
